using Display.Production;
using System.Collections;
using System.Collections.Generic;
using System.Security.Cryptography.X509Certificates;
using UnityEngine;
using UnityEngine.UIElements;

public class Camera4Move : MonoBehaviour
{
    public GameObject Main_Camera;

    public GameObject Black_Camera;
    public GameObject camera4;

    private float camera4X = 0;
    private float camera4Y = 0;
    private float camera4Z = 0;

    public GameObject ListUI;
    public GameObject Panel;

    // Update is called once per frame
    void Update()
    {
        //ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Iï¿½ğ’†‚Ìê‡
        if((ListUI.activeSelf) && (ProductionManager.selectedGameObjects.Count != 0))
        {
            //4ï¿½Â‚ÌƒJï¿½ï¿½ï¿½ï¿½ï¿½ÌˆÚ“ï¿½ï¿½Ê’u
            camera4X = (GlobalVariables.workNumber % 2) == 0 ? 5.0f : 0.0f;
            camera4Y = (GlobalVariables.workNumber % 2) == 0 ? camera4Y : camera4Y - 125.0f;
            OnClick();
        }           
    }

    public void OnClick()
    {
        Main_Camera.SetActive(false);
        Black_Camera.SetActive(true);
        //ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½ÌˆÊ’uï¿½Ú“ï¿½ï¿½ÆƒAï¿½Nï¿½eï¿½Bï¿½u
        camera4.transform.position = new Vector3(camera4X, camera4Y, camera4Z);
        camera4.SetActive(true);
    }
}
